
ALTER TABLE public.trading_bots 
ADD COLUMN IF NOT EXISTS tier text NOT NULL DEFAULT 'free',
ADD COLUMN IF NOT EXISTS description text DEFAULT '',
ADD COLUMN IF NOT EXISTS daily_earn numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS min_stake numeric NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS bot_users integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS runs integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_ai boolean NOT NULL DEFAULT false;
